{{- if .Values.logging.serviceAccount.create }}
{{- $loggingServiceAccountName := include "container-agent.logging.serviceAccountName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.logging.serviceAccount.secret.name }}
  annotations:
    kubernetes.io/service-account.name: {{ $loggingServiceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}
