{{- if .Values.logging.serviceAccount.create }}
{{- $loggingServiceAccountName := include "container-agent.logging.serviceAccountName" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $loggingServiceAccountName }}
{{- if .Values.logging.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.logging.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
