{{- if .Values.agent.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "container-agent.fullname" . }}
spec:
  {{- if and .Values.agent.pdb.minAvailable (not (hasKey .Values.agent.pdb "maxUnavailable")) }}
  minAvailable: {{ .Values.agent.pdb.minAvailable }}
  {{- else if .Values.agent.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.agent.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.agent.matchLabels | nindent 6 }}
{{- end }}
