{{- if and (or .Values.proxy.http.auth.enabled .Values.proxy.https.auth.enabled) (or (not (empty .Values.proxy.http.auth.password)) (not (empty .Values.proxy.https.auth.password))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-agent.fullname" . }}-proxy-credentials
  namespace: {{ .Release.Namespace | quote }}
stringData:
  http-username: {{ .Values.proxy.http.auth.username }}
  http-password: {{ .Values.proxy.http.auth.password }}
  https-username: {{ .Values.proxy.https.auth.username }}
  https-password: {{ .Values.proxy.https.auth.password }}
{{- end }}