{{- $serviceAccountName := include "container-agent.serviceAccountName" . }}
{{- $fullname := include "container-agent.fullname" . }}
{{- if .Values.rbac.create }}
{{- $role := .Values.rbac.role }}
{{- $name := printf "%s:%s" $fullname $role.name | quote }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["", "events.k8s.io/v1"]
    resources: ["events"]
    verbs: ["watch", "list"]

  {{- if .Values.agent.ssh.enabled }}
  - apiGroups: ["", "gateway.networking.k8s.io"]
    resources: ["gateways", "services"]
    verbs: ["get"]
  {{- end }} # if .Values.agent.ssh.enabled

{{- if $role.rules }}
  {{- toYaml $role.rules | nindent 2 }}
{{- end }} # if $role.rules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
{{- end }} # if .Values.rbac.create