{{- $serviceAccountName := include "container-agent.serviceAccountName" . }}
{{- $namespace := .Release.Namespace | quote }}
{{- $fullname := include "container-agent.fullname" . }}
{{- if .Values.rbac.create }}
{{- $role := .Values.rbac.role }}
{{- $name := printf "%s:%s" $fullname $role.name | quote }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["", "events.k8s.io/v1"]
    resources: ["events"]
    verbs: ["watch"]

  {{- if .Values.agent.ssh.enabled }}
  - apiGroups: ["", "gateway.networking.k8s.io"]
    resources: ["gateways", "services"]
    verbs: ["get"]
  {{- end }} # if .Values.agent.ssh.enabled

{{- if $role.rules }}
  {{- toYaml $role.rules | indent 2 }}
{{- end }} # if $role.rules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
{{- end }} # if .Values.rbac.create

{{- if .Values.logging.rbac.create }}
{{- $loggingServiceAccountName := include "container-agent.logging.serviceAccountName" . }}
{{- $loggingRole := .Values.logging.rbac.role }}
{{- $loggingName := printf "%s:%s" $fullname $loggingRole.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $loggingName }}
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
{{- if $loggingRole.rules }}
  {{- toYaml $loggingRole.rules | indent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $loggingName }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $loggingServiceAccountName }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $loggingName }}
{{- end }} # if .Values.logging.rbac.create
