{{- $namespace := .Release.Namespace | quote }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container-agent.serviceAccountName" . }}
  namespace: {{ $namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if .Values.logging.serviceAccount.create }}
{{- $loggingServiceAccountName := include "container-agent.logging.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $loggingServiceAccountName }}
  namespace: {{ $namespace }}
{{- if .Values.logging.serviceAccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.logging.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.logging.serviceAccount.secret.name }}
  namespace: {{ $namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $loggingServiceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}
